[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "clarifycoder_agent"
version = "0.1.0"
description = "ClarifyCoder agent package"
authors = [
    { name = "Your Name", email = "you@example.com" }
]
dependencies = []
